# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
map1 = <<-TEXT
WWWWWWWWWWWWWWWWWWWW
WOOOOOOOOOOOOOOOOOOW
WOOWOWOWOOOWOOWWOWOW
WOOOOOOOWOOWOOOOWWOW
WOOWOWOOWOOWOOWWWWOW
WOOWOWWOWOOWOOWOOWOW
WOOWOOWOWOOWOOWOOWOW
WOOOWOWOWOOWOOOOOWOW
WOOOWOWOWOOWOOWOOWOW
WOOOWWWOWOOWOOWWWWOW
WOOOOOOOOOOOOOOOOOOW
WOOWOWOWOOOWOOWWOWOW
WOOOOOOOWOOWOOOOOWOW
WOOWOWOWWWWWOOWWOWOW
WOOOOOOOWOOWOOOOOWOW
WOOWWWWWWWOWOOWWOWOW
WOOOOWOOOOOWOOOOOWOW
WOOOOWOWWWOWOOWWOWOW
WOOOOOOOOWOOOOOOOOOW
WWWWWWWWWWWWWWWWWWWW
TEXT
map2 = <<-TEXT
WWWWWWWWWWW
WOOOOOOWOOW
WOOWWOOOOOW
WOOOOOOWWOW
WOWWOOOWWOW
WOWWOOOWWOW
WOOWWOOWWOW
WOOOWWOWWOW
WOOOOOOWWOW
WOWWWOOWOOW
WOOOWOOOOOW
WOWWWOOWWOW
WOOOOOOWWWW
WOWOWOOWWOW
WOWWWOOWWOW
WOOOOOOWOOW
WWWOOOOWOWW
WWWWWWWWWWW
TEXT
GameRoom.create!(map_terrain: map1, map_objects: nil, map_width: 20, map_height: 20);
GameRoom.create!(map_terrain: map2, map_objects: nil, map_width: 11, map_height: 18);
